const url=import.meta.env.VITE_API_KEY;

export const routes={
    signup:`${url}/api/auth/signup`,
    login:`${url}/api/auth/login`,
    getData:`${url}/api/user/box`,
    getBox:`${url}/api/user/box`,
    invitations:`${url}/api/group/my-invitations`,
    acceptinvite:`${url}/api/group/accept-userInvite`,
    createGroup:`${url}/api/group/create-group`,
    inviteGroup:`${url}/api/group/invite-group`,
    mygroup:`${url}/api/group/my-groups`,
    groupDetail:`${url}/api/group/get-group-detail`,
    createTemporary:`${url}/api/booking/create-temporary`,
    createPayment:`${url}/api/booking/create-order`,
    verifyPayment:`${url}/api/booking/confirm`,
    isAvailable:`${url}/api/booking/is-available`,
    createSettlement:`${url}/api/settlement/create`,
    viewSettlement:`${url}/api/settlement/group`,
    viewMySettlement:`${url}/api/settlement`,
    verifyEmail:`${url}/api/auth/verify`,
    isAdmin:`${url}/api/settlement/isAdminofSettlement`,
    createMatch:`${url}/api/settlement/create-match`,
    viewMatchId:`${url}/api/settlement/get-matchid`,
    getMembers:`${url}/api/settlement/get-member`,
    getScorecard:`${url}/api/matches/my-matches`,
    profile:`${url}/api/auth/profile`,
    UserProfile:`${url}/api/auth/user`,
    ForgetPassword:`${url}/api/auth/forget-password`,
    nickname:`${url}/api/group/nicknames`,
    groupDetail:`${url}/api/group/get-group-detail`,
    createSettlement:`${url}/api/settlement/create`,
    getGroup:`${url}/api/settlement/group`,
    myStatus:`${url}/api/settlement`,
    myBookings:`${url}/api/booking/my-bookings`,
    mySettlemetn:`${url}/api/settlement`,
    reminder:`${url}/api/settlement/reminder`,
}
